import { describe, expect, it } from 'vitest'
import { EVENT_KINDS, SEVERITIES, validateCyberEvent, validateCyberEventStream } from './schema'

// Independent copy of the frozen document's example; not generated by the SUT.
const example = () => ({
  schema_version: '1.0', event_id: 'scan-001', timestamp: '2026-09-18T00:00:01Z', event_kind: 'SCAN',
  data_mode: 'SIMULATED', provenance_class: 'SIMULATED', evidence_level: 'ILLUSTRATIVE', scope: 'GLOBAL',
  source: { country_code: 'ZZ', display_lat: 10, display_lon: 20, geo_is_actor: false },
  target: { display_name: 'Simulation Target A', country_code: 'ZZ', display_lat: 30, display_lon: 40, target_class: 'demo' },
  severity: 'LOW', confidence: 0.8, feed_source: 'scenario-generator', scenario_id: 'global-noise-v1', seed: '42', metadata: {},
})

describe('CyberEvent v1.0 validation', () => {
  it.each(EVENT_KINDS)('accepts the document example with kind %s', event_kind => {
    expect(validateCyberEvent({ ...example(), event_kind })).toBe(true)
  })
  it.each(SEVERITIES)('accepts visual severity %s', severity => {
    expect(validateCyberEvent({ ...example(), severity })).toBe(true)
  })
  it('accepts boundary values, UTC fractional seconds, reserved dedup key and safe JSON', () => {
    expect(validateCyberEvent({ ...example(), timestamp: '2024-02-29T23:59:59.123456+00:00' })).toBe(true)
    for (const confidence of [0, 1]) {
      expect(validateCyberEvent({ ...example(), confidence, timestamp: '2024-02-29T23:59:59.12Z',
        source: { ...example().source, display_lat: -90, display_lon: 180 },
        target: { ...example().target, display_lat: 90, display_lon: -180 },
        metadata: { visual: { step: 1, labels: ['demo'], enabled: true, detail: null } }, dedup_key: 'reserved',
      })).toBe(true)
    }
  })
  it.each([
    ['schema_version', '2.0'], ['event_kind', 'BREACH'], ['event_kind', 'COMPROMISED'], ['event_kind', 'scan'],
    ['data_mode', 'REAL'], ['data_mode', 'PUBLIC_PROVIDER'], ['provenance_class', 'PUBLIC_CTI'],
    ['evidence_level', 'OBSERVED'], ['scope', 'ORGANIZATION'], ['feed_source', 'public-provider'],
    ['severity', 'URGENT'], ['confidence', -0.1], ['confidence', 1.01], ['confidence', NaN],
    ['confidence', Infinity], ['confidence', '0.8'], ['event_id', '  '], ['event_id', 'COMPROMISED-1'],
    ['scenario_id', 'global-noise'], ['seed', '192.0.2.1'], ['seed', '2001:db8::1'],
    ['metadata', []], ['metadata', null], ['dedup_key', undefined],
  ])('rejects invalid %s=%s', (field, value) => {
    expect(validateCyberEvent({ ...example(), [field]: value })).toBe(false)
  })
  it.each([
    '2026-02-30T00:00:00Z', '2025-02-29T00:00:00Z', '2026-13-01T00:00:00Z',
    '2026-09-18T24:00:00Z', '2026-09-18T00:00:60Z', '2026-09-18T00:00:01',
    '2026-09-18T00:00:01+02:00', 'yesterday', '',
  ])('rejects invalid or non-UTC timestamp %s', timestamp => {
    expect(validateCyberEvent({ ...example(), timestamp })).toBe(false)
  })
  it('requires every mandatory field and rejects unknown fields at each level', () => {
    for (const field of Object.keys(example())) {
      const event: Record<string, unknown> = example()
      delete event[field]
      expect(validateCyberEvent(event), field).toBe(false)
    }
    expect(validateCyberEvent({ ...example(), unexpected: {} })).toBe(false)
    for (const part of ['source', 'target'] as const) {
      expect(validateCyberEvent({ ...example(), [part]: { ...example()[part], extra: {} } })).toBe(false)
      for (const field of Object.keys(example()[part])) {
        const geography: Record<string, unknown> = { ...example()[part] }
        delete geography[field]
        expect(validateCyberEvent({ ...example(), [part]: geography })).toBe(false)
      }
    }
  })
  it('rejects attribution and unsafe geography while preserving display-only semantics', () => {
    for (const geo_is_actor of [true, 'false', 0, null, undefined]) {
      expect(validateCyberEvent({ ...example(), source: { ...example().source, geo_is_actor } })).toBe(false)
    }
    for (const part of ['source', 'target'] as const) {
      for (const [field, value] of [['display_lat', 91], ['display_lat', -91], ['display_lon', 181], ['display_lon', -181], ['display_lat', NaN], ['display_lon', Infinity], ['display_lat', '10'], ['country_code', 'USA']]) {
        expect(validateCyberEvent({ ...example(), [part]: { ...example()[part], [field]: value } })).toBe(false)
      }
    }
    expect(validateCyberEvent({ ...example(), source: { ...example().source, actor: 'Named group' } })).toBe(false)
  })
  it.each(['Named organization', 'Microsoft', 'Simulation Target Microsoft', '192.0.2.1', 'COMPROMISED'])('rejects target claim %s even with simulated provenance', display_name => {
    expect(validateCyberEvent({ ...example(), target: { ...example().target, display_name } })).toBe(false)
  })
  it.each([
    { actor: 'Named group' }, { actorIdentity: 'Named group' }, { organization: 'Microsoft' },
    { ip_address: '192.0.2.1' }, { note: '2001:db8::1' }, { ioc: 'abc' }, { vulnerability: 'CVE-2026-1234' },
    { provider: 'external' }, { raw_payload: {} }, { status: 'COMPROMISED' }, { note: 'BREACH' },
    { data_mode: 'SIMULATED' }, { scope: 'GLOBAL' }, { geo_is_actor: true }, { note: 'APT28' },
    { attack_success: true }, { source: { name: 'group' } }, { note: 'https://example.com' }, { note: 'unsafe.example' },
  ])('rejects unsafe metadata at arbitrary nesting depth %j', unsafe => {
    expect(validateCyberEvent({ ...example(), metadata: { nested: [{ deeper: unsafe }] } })).toBe(false)
  })
  it('rejects non-JSON metadata, cycles, accessors and prototype pollution keys', () => {
    const cycle: Record<string, unknown> = {}
    cycle.self = cycle
    for (const metadata of [cycle, { value: undefined }, { value: NaN }, { value: () => 1 }, { value: new Date() }, JSON.parse('{"__proto__": {}}'), { [Symbol('hidden')]: 'value' }]) {
      expect(validateCyberEvent({ ...example(), metadata })).toBe(false)
    }
    const getter = { get note() { throw new Error('must not execute') } }
    expect(validateCyberEvent({ ...example(), metadata: getter })).toBe(false)
    expect(validateCyberEvent(null)).toBe(false)
    expect(validateCyberEvent([])).toBe(false)
  })
  it('rejects cross-field scope/provenance claims and scenario-local duplicate IDs', () => {
    expect(validateCyberEvent({ ...example(), data_mode: 'REAL', scope: 'ORGANIZATION' })).toBe(false)
    expect(validateCyberEvent({ ...example(), provenance_class: 'PUBLIC_CTI', target: { ...example().target, display_name: 'Named organization' } })).toBe(false)
    expect(validateCyberEventStream([example(), example()])).toBe(false)
    expect(validateCyberEventStream(Array(2))).toBe(false)
    expect(validateCyberEventStream([example(), { ...example(), event_id: 'scan-002' }])).toBe(true)
    expect(validateCyberEventStream([example(), { ...example(), scenario_id: 'global-noise-v2' }])).toBe(true)
    expect(validateCyberEventStream([example(), { ...example(), event_kind: 'BREACH' }])).toBe(false)
  })
})
